# Generated by Django 5.0.7 on 2024-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RicoveroTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceOspedale', models.CharField(max_length=10)),
                ('codiceRicovero', models.CharField(max_length=20)),
                ('paziente', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
                ('durata', models.IntegerField()),
                ('motivo', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
