# Generated by Django 5.0.7 on 2024-07-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patologiatable',
            name='titolo',
        ),
    ]
